language: go

os:
  - linux
  - osx

compiler:
  - gcc

go:
  - "1.11.x"

env:
  - GO111MODULE=on

install:
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - diff <(goimports -d .) <(printf "")
  - make install
  - make test
