language: go

os:
  - linux
  - osx

go:
  - "1.11.x"
  - "1.12.x"
  - "1.13.x"

env:
  - GO111MODULE=on

addons:
  apt:
    packages:
      - gcc

before_install:
  - if [[ "TRAVIS_OS_NAME" == "osx" ]]; then brew update     ; fi
  - if [[ "TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc; fi

install:
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - diff <(goimports -d .) <(printf "")
  - make install
  - make test
