language: go

os:
  - linux
  - osx

go:
  - "1.10.x"
  - "1.11.x"

env:
  - GO111MODULE=on

install:
  - go get -t -v ./...
  - go get -u golang.org/x/tools/cmd/goimports

script:
  - diff <(goimports -d .) <(printf "")
  - make test
